"""
report.py
---------
Builds and saves the Milestone 1 sentiment report from fully processed
records (ingestion + preprocessing + sentiment already applied).

Produces:
    - A machine-readable CSV report (primary format).
    - An optional simple human-readable HTML report.
    - A summary dict (total / positive / negative / neutral counts).
"""

import logging
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)

REPORT_COLUMNS = [
    "employee_id",
    "original_text",
    "processed_text",
    "classification",
    "compound",
    "positive",
    "negative",
    "neutral",
]


def build_report_rows(records: list) -> list:
    """
    Convert a list of fully processed records into flat report rows.

    Each input record is expected to look like:
        {
            "employee_id": ...,
            "original_text": ...,
            "processed_text": ...,
            "sentiment": {
                "positive": ..., "negative": ..., "neutral": ...,
                "compound": ..., "classification": ...,
            },
        }
    """
    rows = []
    for record in records:
        sentiment = record.get("sentiment", {})
        rows.append({
            "employee_id": record.get("employee_id"),
            "original_text": record.get("original_text", ""),
            "processed_text": record.get("processed_text", ""),
            "classification": sentiment.get("classification"),
            "compound": sentiment.get("compound"),
            "positive": sentiment.get("positive"),
            "negative": sentiment.get("negative"),
            "neutral": sentiment.get("neutral"),
        })
    return rows


def compute_summary(rows: list) -> dict:
    """Compute total/positive/negative/neutral counts from report rows."""
    summary = {
        "total_samples": len(rows),
        "positive_count": sum(1 for r in rows if r["classification"] == "Positive"),
        "negative_count": sum(1 for r in rows if r["classification"] == "Negative"),
        "neutral_count": sum(1 for r in rows if r["classification"] == "Neutral"),
    }
    return summary


def save_csv_report(rows: list, output_path) -> Path:
    """Save report rows to a CSV file, creating parent directories as needed."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    df = pd.DataFrame(rows, columns=REPORT_COLUMNS)
    df.to_csv(output_path, index=False)
    logger.info("CSV report saved: %s (%d row(s)).", output_path, len(rows))
    return output_path


def save_html_report(rows: list, summary: dict, output_path) -> Path:
    """Save a simple human-readable HTML report, including the summary."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    df = pd.DataFrame(rows, columns=REPORT_COLUMNS)
    table_html = df.to_html(index=False, na_rep="")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Employee Wellness — Baseline Sentiment Report</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 2rem; color: #222; }}
  h1 {{ font-size: 1.4rem; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1rem; }}
  th, td {{ border: 1px solid #ccc; padding: 6px 10px; text-align: left; font-size: 0.9rem; }}
  th {{ background: #f2f2f2; }}
  .summary {{ margin-top: 1rem; }}
  .note {{ margin-top: 2rem; font-size: 0.8rem; color: #666; }}
</style>
</head>
<body>
  <h1>AI-Based Employee Wellness Platform — Baseline Sentiment Report</h1>
  <div class="summary">
    <p><strong>Total Samples:</strong> {summary['total_samples']}</p>
    <p><strong>Positive:</strong> {summary['positive_count']} &nbsp;
       <strong>Negative:</strong> {summary['negative_count']} &nbsp;
       <strong>Neutral:</strong> {summary['neutral_count']}</p>
  </div>
  {table_html}
  <p class="note">
    Sentiment scores are generated by VADER and are a textual signal only.
    They do not constitute a medical or psychological diagnosis.
  </p>
</body>
</html>
"""
    output_path.write_text(html, encoding="utf-8")
    logger.info("HTML report saved: %s.", output_path)
    return output_path


def generate_report(records: list, csv_path, html_path=None) -> dict:
    """
    High-level entry point: build rows, compute summary, save CSV (and
    optionally HTML).

    Returns:
        {"rows": [...], "summary": {...}, "csv_path": Path, "html_path": Path|None}
    """
    rows = build_report_rows(records)
    summary = compute_summary(rows)

    saved_csv = save_csv_report(rows, csv_path)
    saved_html = save_html_report(rows, summary, html_path) if html_path else None

    return {
        "rows": rows,
        "summary": summary,
        "csv_path": saved_csv,
        "html_path": saved_html,
    }
